### ISSUE TITLE
Unable to use virtualenv.

### ISSUE THREAD

**Issue by dsully** [Richardk2n/pylsp-mypy#17]
Because `pylsp-mypy` imports `mypy.api` in the context of `python-lsp-server`, if one is working in a virtualenv mypy is unable to type check properly.

Other linters such as `flake8` work, as they are forking and inherit the environment properly.

Any objection to updating this to call `mypy` via `subprocess.run()` ?

**Comment by Richardk2n** [comment]
My only concern would be:
Can this cause problems as in decreased speed or race conditions?
If not I would happily merge a pull request. (In terms of writing it myself, could be a week or two until i have time)

It would be nice if you could link an example how other linters do it, because I would assume, that it is save to do something similar.

**Comment by dsully** [comment]
Given that mypy already needs to run on whole files and usually needs to scan entire directories I'm not too worried about the speed of a library call vs fork & exec.

https://github.com/dense-analysis/ale/blob/7d8fb2ba1716a744446b811fc278ecf30d4eb771/ale_linters/python/mypy.vim

Is an example.

**Comment by jpneverwas** [comment]
Howdy folks, I'm slightly saddened by the collective suffering expressed here because (unless I've totally lost it) this has been a mostly solved problem upstream for a good minute now, at least for the basic use case described. Unfortunately, I've only just discovered this fork because python-lsp-server isn't yet part of my "carefully audited" (outdated) toolset. Anyway, #22 attempts to deal with it in a more general way, which some may find objectionable (though I'd be happy to bend to your will). Please check it out, if you dare. Thanks.

**Comment by dsully** [comment]
@jpneverwas - curious what you mean by "mostly solved problem upstream" ?

**Comment by jpneverwas** [comment]
Dan Sully ***@***.***> writes:

> @jpneverwas - curious what you mean by "mostly solved problem upstream" ?

Last I checked, the python-executable option still doesn't work for
stubgen (with Python 3).

**Comment by meshy** [comment]
@dsully thank you for opening this issue, and working out that calling with subprocess might fix this. I've opened https://github.com/Richardk2n/pylsp-mypy/pull/23 to switch over to it, and can confirm that this fixes the issue for me.
